var IE6 = $.browser.msie && $.browser.version == '6.0';
;(function(d){var k=d.scrollTo=function(a,i,e){d(window).scrollTo(a,i,e)};k.defaults={axis:'xy',duration:parseFloat(d.fn.jquery)>=1.3?0:1};k.window=function(a){return d(window)._scrollable()};d.fn._scrollable=function(){return this.map(function(){var a=this,i=!a.nodeName||d.inArray(a.nodeName.toLowerCase(),['iframe','#document','html','body'])!=-1;if(!i)return a;var e=(a.contentWindow||a).document||a.ownerDocument||a;return d.browser.safari||e.compatMode=='BackCompat'?e.body:e.documentElement})};d.fn.scrollTo=function(n,j,b){if(typeof j=='object'){b=j;j=0}if(typeof b=='function')b={onAfter:b};if(n=='max')n=9e9;b=d.extend({},k.defaults,b);j=j||b.speed||b.duration;b.queue=b.queue&&b.axis.length>1;if(b.queue)j/=2;b.offset=p(b.offset);b.over=p(b.over);return this._scrollable().each(function(){var q=this,r=d(q),f=n,s,g={},u=r.is('html,body');switch(typeof f){case'number':case'string':if(/^([+-]=)?\d+(\.\d+)?(px|%)?$/.test(f)){f=p(f);break}f=d(f,this);case'object':if(f.is||f.style)s=(f=d(f)).offset()}d.each(b.axis.split(''),function(a,i){var e=i=='x'?'Left':'Top',h=e.toLowerCase(),c='scroll'+e,l=q[c],m=k.max(q,i);if(s){g[c]=s[h]+(u?0:l-r.offset()[h]);if(b.margin){g[c]-=parseInt(f.css('margin'+e))||0;g[c]-=parseInt(f.css('border'+e+'Width'))||0}g[c]+=b.offset[h]||0;if(b.over[h])g[c]+=f[i=='x'?'width':'height']()*b.over[h]}else{var o=f[h];g[c]=o.slice&&o.slice(-1)=='%'?parseFloat(o)/100*m:o}if(/^\d+$/.test(g[c]))g[c]=g[c]<=0?0:Math.min(g[c],m);if(!a&&b.queue){if(l!=g[c])t(b.onAfterFirst);delete g[c]}});t(b.onAfter);function t(a){r.animate(g,j,b.easing,a&&function(){a.call(this,n,b)})}}).end()};k.max=function(a,i){var e=i=='x'?'Width':'Height',h='scroll'+e;if(!d(a).is('html,body'))return a[h]-d(a)[e.toLowerCase()]();var c='client'+e,l=a.ownerDocument.documentElement,m=a.ownerDocument.body;return Math.max(l[h],m[h])-Math.min(l[c],m[c])};function p(a){return typeof a=='object'?a:{top:a,left:a}}})(jQuery);
//includes
(function($){$.extend({ImportBasePath:'',fileinfo:function(data){data=data.replace(/^\s|\s$/g,"");var m;if(/\.\w+$/.test(data)){m=data.match(/([^\/\\]+)\.(\w+)$/);if(m){if(m[2]=='js'){return{filename:m[1],ext:m[2],tag:'script'}}else if(m[2]=='css'){return{filename:m[1],ext:m[2],tag:'link'}}else{return{filename:m[1],ext:m[2],tag:null}}}else{return{filename:null,ext:null}}}else{m=data.match(/([^\/\\]+)$/);if(m){return{filename:m[1],ext:null,tag:null}}else{return{filename:null,ext:null,tag:null}}}},fileExist:function(filename,filetype,attrCheck){var elementsArray=document.getElementsByTagName(filetype);for(var i=0;i<elementsArray.length;i++){if(elementsArray[i].getAttribute(attrCheck)==$.ImportBasePath+filename){return true}}return false},createElement:function(filename,filetype){switch(filetype){case'script':if(!$.fileExist(filename,filetype,'src')){var scriptTag=document.createElement(filetype);scriptTag.setAttribute('language','javascript');scriptTag.setAttribute('type','text/javascript');scriptTag.setAttribute('src',$.ImportBasePath+filename);return scriptTag}else{return false}break;case'link':if(!$.fileExist(filename,filetype,'href')){var styleTag=document.createElement(filetype);styleTag.setAttribute('type','text/css');styleTag.setAttribute('rel','stylesheet');styleTag.setAttribute('href',$.ImportBasePath+filename);return styleTag}else{return false}break;default:return false;break}},cssReady:function(index,callback){function check(){if(document.styleSheets[index]){if(typeof callback=='function'){callback()}window.clearInterval(checkInterval)}}var checkInterval=window.setInterval(check,200)},include:function(file,callback){var headerTag=document.getElementsByTagName('head')[0];var fileArray=[];typeof file=='string'?fileArray[0]=file:fileArray=file;for(var i=0;i<fileArray.length;i++){var elementTag=$.fileinfo(fileArray[i]).tag;var el=[];if(elementTag!==null){el[i]=$.createElement(fileArray[i],elementTag);if(el[i]){headerTag.appendChild(el[i]);if($.browser.msie){el[i].onreadystatechange=function(){if(this.readyState==='loaded'||this.readyState==='complete'){if(typeof callback=='function'){callback()}}}}else{if(elementTag=='link'){$.cssReady(i,callback)}else{el[i].onload=function(){if(typeof callback=='function'){callback()}}}}}}else{return false}}}})})(jQuery);
//lazy load 
LazyLoad=function(){var f=document,g,b={},e={css:[],js:[]},a;function j(l,k){var m=f.createElement(l),d;for(d in k){if(k.hasOwnProperty(d)){m.setAttribute(d,k[d])}}return m}function h(d){var l=b[d];if(!l){return}var m=l.callback,k=l.urls;k.shift();if(!k.length){if(m){m.call(l.scope||window,l.obj)}b[d]=null;if(e[d].length){i(d)}}}function c(){if(a){return}var k=navigator.userAgent,l=parseFloat,d;a={gecko:0,ie:0,opera:0,webkit:0};d=k.match(/AppleWebKit\/(\S*)/);if(d&&d[1]){a.webkit=l(d[1])}else{d=k.match(/MSIE\s([^;]*)/);if(d&&d[1]){a.ie=l(d[1])}else{if((/Gecko\/(\S*)/).test(k)){a.gecko=1;d=k.match(/rv:([^\s\)]*)/);if(d&&d[1]){a.gecko=l(d[1])}}else{if(d=k.match(/Opera\/(\S*)/)){a.opera=l(d[1])}}}}}function i(r,q,s,m,t){var n,o,l,k,d;c();if(q){q=q.constructor===Array?q:[q];if(r==="css"||a.gecko||a.opera){e[r].push({urls:[].concat(q),callback:s,obj:m,scope:t})}else{for(n=0,o=q.length;n<o;++n){e[r].push({urls:[q[n]],callback:n===o-1?s:null,obj:m,scope:t})}}}if(b[r]||!(k=b[r]=e[r].shift())){return}g=g||f.getElementsByTagName("head")[0];q=k.urls;for(n=0,o=q.length;n<o;++n){d=q[n];if(r==="css"){l=j("link",{href:d,rel:"stylesheet",type:"text/css"})}else{l=j("script",{src:d})}if(a.ie){l.onreadystatechange=function(){var p=this.readyState;if(p==="loaded"||p==="complete"){this.onreadystatechange=null;h(r)}}}else{if(r==="css"&&(a.gecko||a.webkit)){setTimeout(function(){h(r)},50*o)}else{l.onload=l.onerror=function(){h(r)}}}g.appendChild(l)}}return{css:function(l,m,k,d){i("css",l,m,k,d)},js:function(l,m,k,d){i("js",l,m,k,d)}}}();
// jquery.jsonp 2.1.2 (c)2010 Julian Aubourg | MIT License
(function(e,b){function d(){}function t(C){c=[C]}function m(C){f.insertBefore(C,f.firstChild)}function l(E,C,D){return E&&E.apply(C.context||C,D)}function k(C){return/\?/.test(C)?"&":"?"}var n="async",s="charset",q="",A="error",r="_jqjsp",w="on",o=w+"click",p=w+A,a=w+"load",i=w+"readystatechange",z="removeChild",g="<script/>",v="success",y="timeout",x=e.browser,f=e("head")[0]||document.documentElement,u={},j=0,c,h={callback:r,url:location.href};function B(C){C=e.extend({},h,C);var Q=C.complete,E=C.dataFilter,M=C.callbackParameter,R=C.callback,G=C.cache,J=C.pageCache,I=C.charset,D=C.url,L=C.data,P=C.timeout,O,K=0,H=d;C.abort=function(){!K++&&H()};if(l(C.beforeSend,C,[C])===false||K){return C}D=D||q;L=L?((typeof L)=="string"?L:e.param(L,C.traditional)):q;D+=L?(k(D)+L):q;M&&(D+=k(D)+escape(M)+"=?");!G&&!J&&(D+=k(D)+"_"+(new Date()).getTime()+"=");D=D.replace(/=\?(&|$)/,"="+R+"$1");function N(S){!K++&&b(function(){H();J&&(u[D]={s:[S]});E&&(S=E.apply(C,[S]));l(C.success,C,[S,v]);l(Q,C,[C,v])},0)}function F(S){!K++&&b(function(){H();J&&S!=y&&(u[D]=S);l(C.error,C,[C,S]);l(Q,C,[C,S])},0)}J&&(O=u[D])?(O.s?N(O.s[0]):F(O)):b(function(T,S,U){if(!K){U=P>0&&b(function(){F(y)},P);H=function(){U&&clearTimeout(U);T[i]=T[o]=T[a]=T[p]=null;f[z](T);S&&f[z](S)};window[R]=t;T=e(g)[0];T.id=r+j++;if(I){T[s]=I}function V(W){(T[o]||d)();W=c;c=undefined;W?N(W[0]):F(A)}if(x.msie){T.event=o;T.htmlFor=T.id;T[i]=function(){T.readyState=="loaded"&&V()}}else{T[p]=T[a]=V;x.opera?((S=e(g)[0]).text="jQuery('#"+T.id+"')[0]."+p+"()"):T[n]=n}T.src=D;m(T);S&&m(S)}},0);return C}B.setup=function(C){e.extend(h,C)};e.jsonp=B})(jQuery,setTimeout);
$(function () {if ($.browser.msie) {$('input:checkbox').click(function () { this.blur();   this.focus();  });     }}); 
//easydrag
(function($){var isMouseDown=false;var currentElement=null;var dropCallbacks={};var dragCallbacks={};var bubblings={};var lastMouseX;var lastMouseY;var lastElemTop;var lastElemLeft;var dragStatus={};var holdingHandler=false;$.getMousePosition=function(e){var posx=0;var posy=0;if(!e)var e=window.event;if(e.pageX||e.pageY){posx=e.pageX;posy=e.pageY;}
else if(e.clientX||e.clientY){posx=e.clientX+document.body.scrollLeft+document.documentElement.scrollLeft;posy=e.clientY+document.body.scrollTop+document.documentElement.scrollTop;}
return{'x':posx,'y':posy};};$.updatePosition=function(e){var pos=$.getMousePosition(e);var spanX=(pos.x-lastMouseX);var spanY=(pos.y-lastMouseY);$(currentElement).css("top",(lastElemTop+spanY));$(currentElement).css("left",(lastElemLeft+spanX));};$(document).mousemove(function(e){if(isMouseDown&&dragStatus[currentElement.id]!='false'){$.updatePosition(e);if(dragCallbacks[currentElement.id]!=undefined){dragCallbacks[currentElement.id](e,currentElement);}
return false;}});$(document).mouseup(function(e){if(isMouseDown&&dragStatus[currentElement.id]!='false'){isMouseDown=false;if(dropCallbacks[currentElement.id]!=undefined){dropCallbacks[currentElement.id](e,currentElement);}
return false;}});$.fn.ondrag=function(callback){return this.each(function(){dragCallbacks[this.id]=callback;});};$.fn.ondrop=function(callback){return this.each(function(){dropCallbacks[this.id]=callback;});};$.fn.dragOff=function(){return this.each(function(){dragStatus[this.id]='off';});};$.fn.dragOn=function(){return this.each(function(){dragStatus[this.id]='on';});};$.fn.setHandler=function(handlerId){return this.each(function(){var draggable=this;bubblings[this.id]=true;$(draggable).css("cursor","");dragStatus[draggable.id]="handler";$("#"+handlerId).css("cursor","move");$("#"+handlerId).mousedown(function(e){holdingHandler=true;$(draggable).trigger('mousedown',e);});$("#"+handlerId).mouseup(function(e){holdingHandler=false;});});}
$.fn.easydrag=function(allowBubbling){return this.each(function(){if(undefined==this.id||!this.id.length)this.id="easydrag"+(new Date().getTime());bubblings[this.id]=allowBubbling?true:false;dragStatus[this.id]="on";$(this).css("cursor","move");$(this).mousedown(function(e){if((dragStatus[this.id]=="off")||(dragStatus[this.id]=="handler"&&!holdingHandler))
return bubblings[this.id];$(this).css("position","absolute");$(this).css("z-index",parseInt(new Date().getTime()/1000));isMouseDown=true;currentElement=this;var pos=$.getMousePosition(e);lastMouseX=pos.x;lastMouseY=pos.y;lastElemTop=this.offsetTop;lastElemLeft=this.offsetLeft;$.updatePosition(e);return bubblings[this.id];});});};})(jQuery);
	
jQuery.fn.extend({
    setCenter: function () {
        var p = {};
        var screenWidth = $(window).width(), screenHeight = $(window).height(); //当前浏览器窗口的 宽高 
        var scrolltop = $(document).scrollTop(); //获取当前窗口距离页面顶部高度 
        p.left = (screenWidth - $(this).width()) / 2;
        p.top = (screenHeight - $(this).height()) / 2 + scrolltop;
        $(this).css({ "left": p.left, "top": p.top });
        return this;
    }
});
 //bgiframe
 (function (a) { a.fn.bgiframe = (a.browser.msie && /msie 6\.0/i.test(navigator.userAgent) ? function (d) { d = a.extend({ top: "auto", left: "auto", width: "auto", height: "auto", opacity: true, src: "javascript:false;" }, d); var c = '<iframe class="bgiframe"frameborder="0"tabindex="-1"src="' + d.src + '"style="display:block;position:absolute;z-index:-1;' + (d.opacity !== false ? "filter:Alpha(Opacity='0');" : "") + "top:" + (d.top == "auto" ? "expression(((parseInt(this.parentNode.currentStyle.borderTopWidth)||0)*-1)+'px')" : b(d.top)) + ";left:" + (d.left == "auto" ? "expression(((parseInt(this.parentNode.currentStyle.borderLeftWidth)||0)*-1)+'px')" : b(d.left)) + ";width:" + (d.width == "auto" ? "expression(this.parentNode.offsetWidth+'px')" : b(d.width)) + ";height:" + (d.height == "auto" ? "expression(this.parentNode.offsetHeight+'px')" : b(d.height)) + ';"/>'; return this.each(function () { if (a(this).children("iframe.bgiframe").length === 0) { this.insertBefore(document.createElement(c), this.firstChild) } }) } : function () { return this }); a.fn.bgIframe = a.fn.bgiframe; function b(c) { return c && c.constructor === Number ? c + "px" : c } })(jQuery);
 //ie checkbox change events
 $(function () { if ($.browser.msie) { $('input:checkbox').click(function () { this.blur(); this.focus(); }); } });

 $jScroller = { info: { Name: "ByRei jScroller Plugin for jQuery", Version: .4, Author: "Markus Bordihn (http://markusbordihn.de)", Description: "Next Generation Autoscroller" }, config: { obj: [], refresh: 30, regExp: { px: /([0-9,.\-]+)px/} }, cache: { timer: 0, init: 0 }, add: function (parent, child, direction, speed, mouse) { if ($(parent).length && $(child).length && direction && speed >= 1) { $(parent).css({ overflow: "hidden" }); $(child).css({ position: "absolute", left: 0, top: 0 }); mouse && $(child).hover(function () { $jScroller.pause($(child), true) }, function () { $jScroller.pause($(child), false) }); $jScroller.config.obj.push({ parent: $(parent), child: $(child), direction: direction, speed: speed, pause: false }) } }, pause: function (obj, status) { if (obj && typeof status !== "undefined") for (var i in $jScroller.config.obj) if ($jScroller.config.obj[i].child.attr("id") === obj.attr("id")) $jScroller.config.obj[i].pause = status }, start: function () { if ($jScroller.cache.timer === 0 && $jScroller.config.refresh > 0) $jScroller.cache.timer = window.setInterval($jScroller.scroll, $jScroller.config.refresh); if (!$jScroller.cache.init) { $(window).focus($jScroller.start); $(window).resize($jScroller.start); $(window).scroll($jScroller.start); $(document).mousemove($jScroller.start); $.browser.msie && window.focus(); $jScroller.cache.init = 1 } }, stop: function () { if ($jScroller.cache.timer) { window.clearInterval($jScroller.cache.timer); $jScroller.cache.timer = 0 } }, "get": { px: function (value) { var result = ""; if (value) if (value.match($jScroller.config.regExp.px)) if (typeof value.match($jScroller.config.regExp.px)[1] !== "undefined") result = value.match($jScroller.config.regExp.px)[1]; return result } }, scroll: function () { for (var i in $jScroller.config.obj) if ($jScroller.config.obj.hasOwnProperty(i)) { var obj = $jScroller.config.obj[i], left = Number($jScroller.get.px(obj.child.css("left")) || 0), top = Number($jScroller.get.px(obj.child.css("top")) || 0), min_height = obj.parent.height(), min_width = obj.parent.width(), height = obj.child.height(), width = obj.child.width(); if (!obj.pause) switch (obj.direction) { case "up": if (top <= -1 * height) top = min_height; obj.child.css("top", top - obj.speed + "px"); break; case "right": if (left >= min_width) left = -1 * width; obj.child.css("left", left + obj.speed + "px"); break; case "left": if (left <= -1 * width) left = min_width; obj.child.css("left", left - obj.speed + "px"); break; case "down": if (top >= min_height) top = -1 * height; obj.child.css("top", top + obj.speed + "px") } } } };

jQuery.cookie=function(key,value,options){if(arguments.length>1&&(value===null||typeof value!=="object")){options=jQuery.extend({},options);if(value===null){options.expires=-1;}
if(typeof options.expires==='number'){var days=options.expires,t=options.expires=new Date();t.setDate(t.getDate()+days);}
return(document.cookie=[encodeURIComponent(key),'=',options.raw?String(value):encodeURIComponent(String(value)),options.expires?'; expires='+options.expires.toUTCString():'',options.path?'; path='+options.path:'',options.domain?'; domain='+options.domain:'',options.secure?'; secure':''].join(''));}
options=value||{};var result,decode=options.raw?function(s){return s;}:decodeURIComponent;return(result=new RegExp('(?:^|; )'+encodeURIComponent(key)+'=([^;]*)').exec(document.cookie))?decode(result[1]):null;};

function StringBuilder(a) {
    this.strings = new Array(); } StringBuilder.prototype.append = function (a) { a && this.strings.push(a) }, StringBuilder.prototype.appendFormat = function () { if (arguments.length == 0) return null; var a = arguments[0]; for (var b = 1; b < arguments.length; b++) { var c = new RegExp("\\{" + (b - 1) + "\\}", "gm"); a = a.replace(c, arguments[b]) } this.strings.push(a) }, StringBuilder.prototype.clear = function () { this.strings.length = 1 }, StringBuilder.prototype.toString = function (a) { return this.strings.join(a ? a : "") }, String.format = function () { if (arguments.length == 0) return null; var a = arguments[0]; for (var b = 1; b < arguments.length; b++) { var c = new RegExp("\\{" + (b - 1) + "\\}", "gm"); a = a.replace(c, arguments[b]) } return a }, String.prototype.escapeHTML = function () { return this.replace(/>/g, "&gt;").replace(/</g, "&lt;").replace(/"/g, "&quot;").replace(/\'/g, "&#39;") }
var DateTime = { now: function () { var ret = new StringBuilder(); var d = new Date(); ret.append(d.getFullYear() + "-"); ret.append(("00" + (d.getMonth() + 1)).slice(-2) + "-"); ret.append(("00" + d.getDate()).slice(-2) + " "); ret.append(("00" + d.getHours()).slice(-2) + ":"); ret.append(("00" + d.getMinutes()).slice(-2) + ":"); ret.append(("00" + d.getSeconds()).slice(-2)); return ret.toString(); }, dateDiff: function (interval, date1, date2) {
    var objInterval = { 'D': 1000 * 60 * 60 * 24, 'H': 1000 * 60 * 60, 'M': 1000 * 60, 'S': 1000, 'T': 1 }; interval = interval.toUpperCase(); var dt1 = Date.parse(date1.replace(/-/g, '/')); var dt2 = Date.parse(date2.replace(/-/g, '/')); try
{ return Math.round((dt2 - dt1) / eval('(objInterval.' + interval + ')')); }
    catch (e)
{ return e.message; } 
}, formatMinutes: function (minutes) { var day = parseInt(Math.floor(minutes / 1440)); var hour = day > 0 ? Math.floor((minutes - day * 1440) / 60) : Math.floor(minutes / 60); var minute = hour > 0 ? Math.floor(minutes - day * 1440 - hour * 60) : minutes; var time = ""; if (day > 0) time += day + "天"; if (hour > 0) time += hour + "小时"; if (minute > 0) time += minute + "分钟"; return time; }, formatSeconds: function (second) { return [parseInt(second / 60 / 60), parseInt(second / 60 % 60), parseInt(second % 60)].join(":").replace(/\b(\d)\b/g, "0$1"); }
};